name = "SBMLImporter"
uuid = "210efffb-c3c8-456d-a807-6f55560b12fe"
version = "2.5.2"

[deps]
Catalyst = "479239e8-5488-4da2-87a7-35f2df7eef83"
DiffEqBase = "2b5f629d-d688-5b77-993f-72d75c75574e"
ForwardDiff = "f6369f11-7733-5829-9624-2563aa707210"
JumpProcesses = "ccbc3e58-028d-4f4c-8cd5-9ae44345cda5"
ModelingToolkit = "961ee093-0014-501f-94e3-6117800e7a78"
PrecompileTools = "aea7be01-6a6a-4083-8856-8a6e6704d82a"
ReactionNetworkImporters = "b4db0fb7-de2a-5028-82bf-5021f5cfa881"
RuntimeGeneratedFunctions = "7e49a35a-f44a-4d26-94aa-eba1b4ca6b47"
SBML = "e5567a89-2604-4b09-9718-f5f78e97c3bb"
SciMLBase = "0bca4576-84f4-4d90-8ffe-ffa030f20462"
Setfield = "efcf1570-3423-57d1-acb7-fd33fddbac46"
SpecialFunctions = "276daf66-3868-5448-9aa4-cd146d93841b"

[weakdeps]
ForwardDiff = "f6369f11-7733-5829-9624-2563aa707210"

[extensions]
SBMLImporterForwardDiffExt = ["ForwardDiff"]

[compat]
Aqua = "0.8"
CSV = "0.10"
Catalyst = "14"
DataFrames = "1.6"
DiffEqBase = "6"
Downloads = "1"
ForwardDiff = "0.10"
JumpProcesses = "9"
ModelingToolkit = "9.46.1"
OrdinaryDiffEq = "6"
PrecompileTools = "1"
ReactionNetworkImporters = "0.15"
RuntimeGeneratedFunctions = "0.5"
SBML = "1.5.1"
SafeTestsets = "0.1"
SciMLBase = "2.39"
Setfield = "1"
SpecialFunctions = "2"
Test = "1"
julia = "1"

[extras]
Aqua = "4c88cf16-eb10-579e-8560-4a9242c79595"
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
Downloads = "f43a241f-c20a-4ad4-852c-f6b1247861c6"
JumpProcesses = "ccbc3e58-028d-4f4c-8cd5-9ae44345cda5"
OrdinaryDiffEq = "1dea7af3-3e70-54e6-95c3-0bf5283fa5ed"
SafeTestsets = "1bc83da4-3b8d-516f-aca4-4fe02f6d838f"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Aqua", "Test", "CSV", "DataFrames", "Downloads", "SafeTestsets", "OrdinaryDiffEq"]
